import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SocialIcons from "./components/SocialIcons";
import MobileNav from "./components/MobileNav";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Rs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Navbar />
        <MobileNav />
        <SocialIcons />
        {children}
        <Footer />
      </body>
    </html>
  );
}